### ISSUE TITLE
debug report

### ISSUE THREAD

**Issue by limitty** [qkgia/OLP-RPCA#2]
according to the paper, there might be a bug in the subfuntion shrink_p(x, T, p).m:
% perform not well:  y = sign(x) .* max(abs(x) - p * T.* (abs(x) + epsilon) .^ (p - 1), 0) .* (abs(x) > T);  
% perform well which make sense by paper:  y = sign(x) .* max(abs(x) - T, 0) .* (abs(x) > T);

**Comment by qkgia** [comment]
Bug fixed. Thanks for your comment.
