### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by W-Jason** [qkgia/OLP-RPCA#3]
Error shrink_p (line 6)
   y = sign(x) .* max(abs(x) - p * T * (abs(x) + epsilon) .^ (p - 1), 0) .* (abs(x) > T);

errror nrpca (line 116)
    E_hat = shrink_p(temp_T, t * w, p); % soft p-thresholding (lp)

Excuse me, i have some questions about this code!
i dont know how to solve“ Matrix dimensions are inconsistent” problem ,the input data is a m*n matrix and the lambda is 0.05. but the result is error

**Comment by qkgia** [comment]
I just updated my code to fix this bug. Thanks for your comment.
